name = "BCJCalibratinator"
uuid = "a89bb55e-884e-48c3-ba05-e3917bd289c9"
authors = ["Joby M. Anthony III", "Daniel S. Kenney"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
julia = "1.10.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
